import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { ChannelGlyph, HubShell } from "@/components/HubShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, Bell, Clapperboard, Compass, Film, MessageCircle, Play, Plus, Radio, Share2, Sparkles, Trophy, Upload, UserPlus, Video } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Link, useLocation, useRoute } from "wouter";

const formatDate = (date: Date | string) => new Date(date).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });

function Gate({ children }: { children: React.ReactNode }) {
  const { isAuthenticated, loading } = useAuth();
  if (loading) return <div className="lane-blank">Loading your creator station…</div>;
  if (!isAuthenticated) return <div className="lane-blank"><Radio className="size-6" /><h2>Your station is waiting.</h2><p>Sign in to publish a signal, create a channel, follow creators, or join the discussion.</p><button className="loop-primary" onClick={startLogin}>Sign in to continue <ArrowRight className="size-4" /></button></div>;
  return <>{children}</>;
}

function MediaTile({ item, portrait = false }: { item: { id: number; title: string; thumbnailUrl: string | null; videoUrl: string; channelName: string; channelHandle: string; channelAccent: string; viewCount: number; publishedAt: Date }; portrait?: boolean }) {
  return <article className={portrait ? "short-tile" : "explore-tile"}><Link href={`/watch/${item.id}`} className="tile-visual">{item.thumbnailUrl ? <img src={item.thumbnailUrl} alt="" /> : <div className="tile-placeholder"><Play className="size-6" /><span>{portrait ? "SHORT" : "VIDEO"}</span></div>}<span className="tile-count">{item.viewCount} views</span></Link><div className="tile-meta"><Link href={`/channel/${item.channelHandle}`}><ChannelGlyph name={item.channelName} color={item.channelAccent} /></Link><div><Link href={`/watch/${item.id}`}>{item.title}</Link><small>{item.channelName} · {formatDate(item.publishedAt)}</small></div></div></article>;
}

export function ShortsLane() {
  const shorts = trpc.media.feed.useQuery({ format: "short", limit: 36 });
  return <HubShell active="Shorts"><section className="lane-intro"><div><span>02 / SHORTS</span><h1>Quick signals.<br /><em>Clear point of view.</em></h1><p>Short-form creator work lives in a distinct lane. Keep it direct, own the footage, and make the context visible.</p></div><div className="lane-intro-note"><Video className="size-5" /> VERTICAL FORMAT<br />BETA UPLOADS / 10 MB</div></section><section className="shorts-wall">{shorts.data?.length ? shorts.data.map((item) => <MediaTile key={item.id} item={item} portrait />) : <div className="lane-blank wide"><Film className="size-7" /><h2>No shorts have been published.</h2><p>Shorts will appear here when creators post vertical signals.</p><Link href="/create" className="loop-outline">Publish a short <ArrowRight className="size-4" /></Link></div>}</section></HubShell>;
}

function DiscussionComposer({ fixedTopic }: { fixedTopic?: "community" | "football" }) {
  const { isAuthenticated } = useAuth();
  const [body, setBody] = useState("");
  const [topic, setTopic] = useState<"community" | "football" | "build">(fixedTopic || "community");
  const utils = trpc.useUtils();
  const post = trpc.media.post.useMutation({ onSuccess: () => { setBody(""); utils.media.community.invalidate(); toast.success("Your signal is live in the community lane."); }, onError: (error) => toast.error(error.message) });
  if (!isAuthenticated) return <div className="composer-locked"><Sparkles className="size-4" /> Sign in to post a signal, question, match read, or build note.<button onClick={startLogin}>Sign in</button></div>;
  return <div className="signal-composer"><textarea value={body} onChange={(event) => setBody(event.target.value)} maxLength={1000} placeholder="Share a thought worth following…" /><div><div className="topic-toggle">{(["community", "football", "build"] as const).map((item) => <button key={item} className={topic === item ? "topic-active" : ""} onClick={() => setTopic(item)}>{item}</button>)}</div><button className="loop-primary" disabled={body.trim().length < 3 || post.isPending} onClick={() => post.mutate({ body, topic })}>{post.isPending ? "Publishing…" : "Publish signal"} <ArrowRight className="size-4" /></button></div></div>;
}

function DiscussionFeed({ topic }: { topic?: "community" | "football" | "build" }) {
  const feed = trpc.media.community.useQuery(topic ? { topic } : undefined);
  if (!feed.data?.length) return <div className="discussion-empty"><MessageCircle className="size-5" /><p>No posts in this lane yet. The first thoughtful signal sets the tone.</p></div>;
  return <div className="discussion-feed">{feed.data.map((post) => <article className="discussion-card" key={post.id}><div className="discussion-head"><ChannelGlyph name={post.channelName} color={post.channelAccent} /><div><Link href={`/channel/${post.channelHandle}`}>{post.channelName}</Link><small>{post.topic} · {formatDate(post.createdAt)}</small></div><span className={`post-topic topic-${post.topic}`}>{post.topic}</span></div><p>{post.body}</p><div className="discussion-stats"><span><Sparkles className="size-3.5" /> {post.reactionCount}</span><span><MessageCircle className="size-3.5" /> {post.commentCount}</span></div></article>)}</div>;
}

export function CommunityLane() { return <HubShell active="Community"><section className="community-layout"><div className="community-main"><div className="lane-intro compact"><div><span>04 / COMMUNITY</span><h1>Conversation is<br /><em>part of the work.</em></h1></div></div><DiscussionComposer /><DiscussionFeed /></div><aside className="community-side"><span>COMMUNITY STANDARD</span><h3>Own your signal.</h3><p>Post work you have the right to share. Do not publish private information, harassment, or unlawful material. More reporting and moderation controls are planned for the production release.</p><Link href="/football">Enter Football Hub <ArrowRight className="size-4" /></Link></aside></section></HubShell>; }

export function FootballHub() { return <HubShell active="Football"><section className="football-hero"><div><span>03 / FOOTBALL HUB</span><h1>Rated Opinionz.<br /><em>Read the game.</em></h1><p>A space for thoughtful football news, player analysis, match reads, and opinion — with context over noise.</p></div><div className="football-board"><span>RATED OPINIONZ BOT</span><strong>CONNECTED<br />WHEN CONFIGURED</strong><p>The assistant lane will summarize sources and clearly label analysis. It is not active in this beta build yet.</p></div></section><section className="football-layout"><div><div className="hub-section-title"><div><span>FOOTBALL / COMMUNITY</span><h2>Current reads.</h2></div></div><DiscussionComposer fixedTopic="football" /><DiscussionFeed topic="football" /></div><aside className="football-side"><Trophy className="size-5" /><h3>Build the football record.</h3><p>Creator channels can post analysis now. Live scores, news providers, player data, and AI summaries need connected data sources before they can be shown as current information.</p></aside></section></HubShell>; }

export function ExploreLane() { const feed = trpc.media.feed.useQuery({ limit: 48 }); return <HubShell active="Explore"><section className="lane-intro"><div><span>05 / EXPLORE</span><h1>Find a new<br /><em>signal station.</em></h1><p>Explore public creator uploads across the EZROME network. Search and recommendations will become available once there is enough real public activity to rank responsibly.</p></div><Link href="/create" className="loop-primary"><Plus className="size-4" /> Start a station</Link></section>{feed.data?.length ? <section className="explore-grid">{feed.data.map((item) => <MediaTile key={item.id} item={item} />)}</section> : <div className="lane-blank wide"><Compass className="size-7" /><h2>Discovery starts with creators.</h2><p>There are no public videos to explore yet. Publish the first signal or invite a creator to open their station.</p></div>}</HubShell>; }

export function WatchPage() {
  const [, params] = useRoute("/watch/:id");
  const id = Number(params?.id);
  const video = trpc.media.watch.useQuery({ id }, { enabled: Number.isFinite(id) && id > 0 });
  const share = trpc.media.share.useMutation();
  const onShare = async () => { if (!video.data) return; const url = `${window.location.origin}/watch/${video.data.id}`; try { if (navigator.share) await navigator.share({ title: video.data.title, url }); else await navigator.clipboard.writeText(url); share.mutate({ id: video.data.id }); toast.success("Share link ready."); } catch { /* The user cancelled native share; no action needed. */ } };
  if (video.isLoading) return <HubShell active="Watch"><div className="lane-blank">Loading this signal…</div></HubShell>;
  if (!video.data) return <HubShell active="Watch"><div className="lane-blank"><Clapperboard className="size-6" /><h2>This video record is unavailable.</h2><Link href="/" className="loop-outline">Return to Watch <ArrowLeft className="size-4" /></Link></div></HubShell>;
  return <HubShell active="Watch"><section className="watch-layout"><div className="watch-main"><video className="watch-player" controls src={video.data.videoUrl} poster={video.data.thumbnailUrl || undefined} /><div className="watch-meta"><span>{video.data.format === "short" ? "SHORT SIGNAL" : "VIDEO SIGNAL"}</span><h1>{video.data.title}</h1><div><Link href={`/channel/${video.data.channelHandle}`} className="watch-channel"><ChannelGlyph name={video.data.channelName} color={video.data.channelAccent} /><span>{video.data.channelName}<small>@{video.data.channelHandle}</small></span></Link><button onClick={onShare} className="watch-action"><Share2 className="size-4" /> Share</button></div></div><div className="watch-description"><span>VIDEO RECORD / {formatDate(video.data.publishedAt)}</span><p>{video.data.description || "This creator has not added a description yet."}</p></div></div><aside className="watch-aside"><span>CREATOR STATION</span><h3>Keep the signal moving.</h3><p>Follow this creator’s public work, shorts, community notes, and future records.</p><Link href={`/channel/${video.data.channelHandle}`} className="loop-outline">Open station <ArrowRight className="size-4" /></Link></aside></section></HubShell>;
}

export function ChannelPage() { const [, params] = useRoute("/channel/:handle"); const channel = trpc.media.channel.useQuery({ handle: params?.handle || "" }, { enabled: Boolean(params?.handle) }); if (channel.isLoading) return <HubShell active="Station"><div className="lane-blank">Loading creator station…</div></HubShell>; if (!channel.data) return <HubShell active="Station"><div className="lane-blank"><Radio className="size-6" /><h2>This station is not public yet.</h2><Link href="/" className="loop-outline">Return to the network</Link></div></HubShell>; const { channel: record, videos } = channel.data; return <HubShell active="Station"><section className="channel-hero" style={{ "--station-accent": record.accentColor } as React.CSSProperties}><ChannelGlyph name={record.displayName} color={record.accentColor} /><div><span>CREATOR STATION / @{record.handle}</span><h1>{record.displayName}</h1><p>{record.bio || "This creator has not added a station note yet."}</p></div><div className="channel-hero-actions"><button className="loop-primary"><UserPlus className="size-4" /> Follow station</button><span>CHANNEL / ACTIVE</span></div></section><section className="channel-content"><div className="hub-section-title"><div><span>PUBLIC MEDIA</span><h2>Signals from this station.</h2></div><Link href="/create">Create your signal <ArrowRight className="size-4" /></Link></div>{videos.length ? <div className="explore-grid">{videos.map((item) => <MediaTile key={item.id} item={{ ...item, channelName: record.displayName, channelHandle: record.handle, channelAccent: record.accentColor }} />)}</div> : <div className="lane-blank wide"><Upload className="size-6" /><h2>No public media yet.</h2><p>This channel exists, but its first video or short has not been published.</p></div>}</section></HubShell>; }

const toBase64 = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] || ""); reader.onerror = reject; reader.readAsDataURL(file); });

export function UploadStudio() {
  const { isAuthenticated } = useAuth(); const [, setLocation] = useLocation(); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [format, setFormat] = useState<"video" | "short">("video"); const [visibility, setVisibility] = useState<"public" | "unlisted">("public"); const [videoFile, setVideoFile] = useState<File | null>(null); const [thumbnailFile, setThumbnailFile] = useState<File | null>(null); const [rights, setRights] = useState(false); const publish = trpc.media.publish.useMutation({ onSuccess: ({ id }) => { toast.success("Your signal has been published."); setLocation(`/watch/${id}`); }, onError: (error) => toast.error(error.message) });
  const submit = async () => { if (!videoFile) return toast.error("Choose a video file first."); if (!rights) return toast.error("Confirm that you have the rights to publish this media."); if (videoFile.size > 10 * 1024 * 1024) return toast.error("This beta accepts videos up to 10 MB."); const video = { name: videoFile.name, type: videoFile.type, base64: await toBase64(videoFile) }; const thumbnail = thumbnailFile ? { name: thumbnailFile.name, type: thumbnailFile.type, base64: await toBase64(thumbnailFile) } : undefined; publish.mutate({ title, description, format, visibility, video, thumbnail }); };
  return <HubShell active="Create">{!isAuthenticated ? <Gate><></></Gate> : <section className="studio-layout"><div className="studio-head"><span>CREATOR STUDIO / BETA</span><h1>Make the<br /><em>next signal.</em></h1><p>Upload original or licensed media for your creator station. This direct beta flow accepts MP4, WebM, or MOV files up to 10 MB. It does not transcode, auto-moderate, or host livestreams.</p></div><form className="studio-form" onSubmit={(event) => { event.preventDefault(); submit(); }}><label>Signal title<input value={title} onChange={(event) => setTitle(event.target.value)} minLength={3} maxLength={120} placeholder="Give the video a clear name" required /></label><label>Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} maxLength={2000} placeholder="Add context, ownership notes, or a call to action" /></label><div className="studio-grid"><label>Format<select value={format} onChange={(event) => setFormat(event.target.value as "video" | "short")}><option value="video">Video</option><option value="short">Short</option></select></label><label>Visibility<select value={visibility} onChange={(event) => setVisibility(event.target.value as "public" | "unlisted")}><option value="public">Public</option><option value="unlisted">Unlisted</option></select></label></div><label className="file-label">Video file<input type="file" accept="video/mp4,video/webm,video/quicktime" onChange={(event) => setVideoFile(event.target.files?.[0] || null)} required /><span>{videoFile ? `${videoFile.name} · ${(videoFile.size / 1024 / 1024).toFixed(1)} MB` : "MP4, WebM, or MOV · 10 MB max"}</span></label><label className="file-label">Thumbnail <input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setThumbnailFile(event.target.files?.[0] || null)} /><span>{thumbnailFile ? thumbnailFile.name : "Optional JPG, PNG, or WebP · 4 MB max"}</span></label><label className="rights-check"><input type="checkbox" checked={rights} onChange={(event) => setRights(event.target.checked)} /> <span>I own this media or have permission to publish it, and it does not contain unlawful, exploitative, or private content.</span></label><button className="loop-primary studio-submit" disabled={publish.isPending || title.trim().length < 3}>{publish.isPending ? "Publishing…" : "Publish to station"} <ArrowRight className="size-4" /></button></form></section>}</HubShell>;
}

export function NotificationsPage() { const { isAuthenticated } = useAuth(); const list = trpc.media.notifications.useQuery(undefined, { enabled: isAuthenticated }); return <HubShell active="Notifications"><section className="notifications-page"><div className="lane-intro compact"><div><span>NOTIFICATIONS</span><h1>Keep up with<br /><em>your signal.</em></h1></div></div>{!isAuthenticated ? <Gate><></></Gate> : list.data?.length ? <div className="notification-list">{list.data.map((item) => <article key={item.id}><Bell className="size-4" /><div><p>{item.message}</p><small>{formatDate(item.createdAt)}</small></div></article>)}</div> : <div className="lane-blank wide"><Bell className="size-6" /><h2>No station alerts yet.</h2><p>Follow, reaction, comment, and system notifications will land here as the network grows.</p></div>}</section></HubShell>; }
