import { Link } from "wouter";
import { ArrowLeft, FileText, Mail, ShieldCheck } from "lucide-react";
import { HubShell } from "@/components/HubShell";

const publisher = "Sixolile Ezrome Mtyhali / EZROME";
const country = "South Africa";
const supportEmail = "REPLACE_WITH_SUPPORT_EMAIL";
const copyrightEmail = "REPLACE_WITH_COPYRIGHT_EMAIL";

function PolicyFrame({ label, title, children }: { label: string; title: string; children: React.ReactNode }) {
  return <HubShell active="Station"><section className="lane-intro compact"><div><span>{label}</span><h1>{title}</h1><p>Owner-review release document for EZROME V1. Replace marked contact fields and have the final text reviewed before relying on it.</p></div><FileText className="size-12 text-cyan-300" /></section><article className="watch-description policy-document">{children}<Link href="/release-checklist" className="loop-outline"><ArrowLeft className="size-4" /> Return to release checklist</Link></article></HubShell>;
}

export function PrivacyPolicyPage() { return <PolicyFrame label="EZROME / PRIVACY" title="Privacy, made visible."><h2>Draft for owner and professional review</h2><p><strong>Publisher:</strong> {publisher}. <strong>Country:</strong> {country}.</p><p>EZROME may process account identity supplied through authentication, creator profile information, videos and thumbnails uploaded by users, community posts, reports, offline-library records, device and usage information needed to operate the service, and support communications.</p><p>EZROME uses this information to authenticate accounts, publish creator content, provide playback and limited offline access, operate moderation and reporting, respond to deletion requests, improve reliability, and prepare source-aware AI assistance. Managed media storage is used for creator files. AI-assisted newsroom drafts remain subject to human approval.</p><p>EZROME should not collect more information than required for these purposes. Users should be able to request access, correction, or deletion through the account controls and the public deletion resource. Retention, third-party sharing, analytics, cookies, security practices, and cross-border processing must be reviewed and finalized against the production configuration.</p><p><Mail className="inline size-4" /> Privacy contact: <strong>{supportEmail}</strong></p></PolicyFrame>; }

export function TermsPage() { return <PolicyFrame label="EZROME / TERMS" title="The rules of the signal."><h2>Draft for owner and professional review</h2><p>EZROME is a culture-aware social and media platform operated by {publisher}. Users must have the rights and permissions needed to upload, publish, download, or share material they submit.</p><p>Users remain responsible for their content. EZROME may restrict, review, remove, or suspend content and accounts when necessary to enforce Community Guidelines, respond to valid copyright or privacy complaints, protect users, or comply with law.</p><p>V1 is free-first. No paid digital entitlement is active in this release candidate. Future digital subscriptions or in-app features will require a separately reviewed purchase, entitlement, refund, and cancellation process.</p><p>These draft terms must be completed with governing law, limitation-of-liability language, age requirements, dispute handling, service availability, and an accurate support process before publication.</p></PolicyFrame>; }

export function CommunityGuidelinesPage() { return <PolicyFrame label="EZROME / COMMUNITY" title="Own your signal."><h2>V1 community standard</h2><p>Share work you have the right to share. Give credit where appropriate, avoid harassment and threats, do not expose private information, and do not use EZROME to facilitate unlawful exploitation or abuse.</p><p>Content can be reported for copyright, harassment, sexual safety, drug-related risk, violence, privacy, spam, or other concerns. Reports enter a human review queue. AI assistance may help organize information, but it does not make the final moderation decision.</p><p>Creators control whether their published videos can be downloaded for limited offline playback. EZROME may restrict offline access when rights, account status, or safety conditions change.</p></PolicyFrame>; }

export function CopyrightPage() { return <PolicyFrame label="EZROME / RIGHTS" title="Report a rights concern."><h2>Copyright and reporting contact</h2><p>To report suspected copyright infringement, include your name, contact information, identification of the work, the EZROME URL or content identifier, a description of the concern, and the statement that your report is accurate to the best of your knowledge.</p><p>Send reports to <strong>{copyrightEmail}</strong>. This placeholder must be replaced with a monitored inbox controlled by the publisher before launch. EZROME may request additional information, restrict access during review, and provide an appeal or correction path.</p><p>Do not send passwords, signing keys, payment credentials, or unrelated personal information in a report.</p></PolicyFrame>; }

export function AccountDeletionPage() { return <PolicyFrame label="EZROME / DATA CONTROL" title="Delete your account."><ShieldCheck className="size-6 text-cyan-300" /><h2>Public deletion resource</h2><p>Signed-in users can request account deletion from <Link href="/settings">Trust & Safety settings</Link>. This creates a reviewable request rather than an irreversible instant action, and the request can be cancelled while it is still pending.</p><p>For a web request outside the app, contact <strong>{supportEmail}</strong> with the account identifier you use for EZROME. Do not send a password. The publisher must replace this draft contact with a working request form or monitored support process and document which account data, creator media, reports, and legally retained records are deleted or retained.</p><p>Google Play requires an in-app deletion path and a web resource when an app allows account creation. The final public resource and the Play Console Data safety answers must match the production behavior.</p></PolicyFrame>; }
